### ISSUE TITLE
Discussion: How to inject recorder configuration into the container

### ISSUE THREAD

**Issue by simonszu** [deisi/docker-ot-recorder#1]
I'd like to discuss how the general settings of recorder (like what MQTT broker to connect to, etc) should get configured here. ot-recorder relies heavily on environment variables, so the configuration could easily be set on container runtime. 

However, you have designed the image to have a dedicated config file, `recorder.conf` and the example docker-compose files even encourage the user to mount the config from the outside, so one can edit them directly and restart the container. AFAIR the config file values override any set environment variables. 

So in the process of streamlining the example compose files (why 2 files?), there should be a definitve rule whether the users should configure recorder via environment variables (and therefore add some sample values to the compose file), or via the config file...

What would you say?

**Comment by deisi** [comment]
> AFAIR the config file values override any set environment variables.

according to the [documentation](https://github.com/owntracks/recorder#configuration-file)
> The following configuration settings may be applied (a Y in column $ means an environment variable of the same name overrides a setting in the config file):
so the environment variables should overwrite the configuration file.


The reason for the default `recorder.conf` file was the OTR_HTTPHOST = "0.0.0.0", without this line the container wont be reachable from the outside, due to the bridging in docker. At https://github.com/owntracks/recorderd they pass it to the container within the [supervisor](https://github.com/owntracks/recorderd/blob/361bb00f08d67e6ec186aa49a2b5ce81fb788bea/supervisord.conf#L23) but this removes the posibility to overwrite this setting for the user.

> there should be a definitve rule whether the users should configure recorder via environment variables  or via the config file

Think so? I mean these two ways are build into ot-recorder itself, I think the container should merle allow the user to choose what ever he prefers. Its up to the documentation to show both ways and let the user pick any he likes.

> compose files (why 2 files?), 

Well no real reason, I just want to provide a ready to use solution with and without mqtt server. I thought about removing the compose files completely and just put them into the readme, but that would mean people would need to copy and past it from there. Not much better in my opinion. Have a better idea?

**Comment by deisi** [comment]
@simonszu I added some documentation. What do you think? I would be happy for feedback.

**Comment by simonszu** [comment]
The documentation is great, and enabled me to write an ansible role for the recorder. However, one issue is still persisting: You are referring to `owntracks/recorder` in your documentation, although the official image is called recorder**d**. If you are referring to your own image, you should change this. 

Is this repository already linked to a image build on Docker hub?

**Comment by deisi** [comment]
> recorderd

I think the name of the official project is: https://github.com/owntracks/recorder
So without a d. Its only the docker image that has this d, but I don't get why, usually d is for systemd services, but we don't have this here, so I decided to not put it. Lets see what the owntracks people will say.

> The documentation is great, and enabled me to write an ansible role for the recorder

Thx :)

> Is this repository already linked to a image build on Docker hub?

Not yet. I have never uploaded anything to Docker hub so I would need to learn how it works. However my goal is to hand this over to the official owntracks project and they would need to put it up there. Thus me putting it there seems to be double work but again lets seen what the owntracks people will say.

**Comment by deisi** [comment]
this has been added to https://github.com/owntracks/docker-recorder now. Thus I will soon close this repository
